- name: Create BIG-IP guest in VMware
  hosts: esxi
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: Check VM deployed
      vmware_guest:
        hostname: vcsa01.hutton.lab
        username: administrator@hutton.lab
        password: Emca/1449/
        name: test_vm_0001
        validate_certs: no
#        vmware_guest_facts: yes
      delegate_to: localhost
      register: vmguest_facts

    - name: saving output
      ansible.builtin.copy:
        content: "{{vmguest_facts}}"
        dest: "/home/murilo/Documents/ANSIBLE_f5_esxi/deploy-output.txt"

    - name: Debug facts
      debug: msg="vmguest facts are {{ vmguest_facts }}"